/* eslint-disable @typescript-eslint/no-explicit-any */
export const suggestedPaperTitles: any[] = [
	'attention is all you need',
	'acid',
	'a theory of justice',
	'augmented',
	'behavioral',
	'books',
	'black hole',
	'brain',
	'cats',
	'computer',
	'creative',
	'dog',
	'dna sequencing',
	'dyson sphere',
	'ecg',
	'emotional',
	'entanglement',
	'fear',
	'fuzzy sets',
	'fidgeting',
	'glucose',
	'garbage',
	'gonad',
	'hands',
	'heart',
	'higgs boson',
	'hydron',
	'identity',
	'industrial',
	'isolation',
	'laptop',
	'love',
	'laboratory',
	'machine learning',
	'mathematical theory of communication',
	'mental state',
	'micro',
	'microchip',
	'mobile',
	'molecular cloning',
	'neural network',
	'negative',
	'numbers',
	'pc',
	'planet',
	'protein measurement',
	'psychology',
	'quantum',
	'quasar',
	'qubit',
	'reading',
	'relationship',
	'relativity',
	'robotics',
	'rocket',
	'sitting',
	'spider',
	'spiritual',
	'sulphur',
	'television',
	'tiered reward',
	'transport',
	'virtual reality',
	'volcano',
	'vision'
];
